category = "mac_centris"
picture_asset_key = "MI000069"
name = "Macintosh Centris 610"
introductions = [{ year = 1993, month = 2 }]

model_numbers = [{ value = "M1444" }]
gestalt_ids = [{ value = "52" }]
order_numbers = [
  { value = "M1345", revisions = ["A"], qualifier = "80 MB hard drive" },
  { value = "M1397", revisions = ["A"], qualifier = "230 MB hard drive" },
  { value = "M1398", revisions = ["A"], qualifier = "230 MB hard drive and CD-ROM" },
]

codenames = [{ value = "Econoline" }, { value = "QFC" }, { value = "WLCD" }]

processor = "**Motorola 68LC040** 20 MHz, 0.8 µm HCMOS process, 32-bit, 4 KB instruction and 4 KB data L1 cache, 20 MHz system bus"
processor_family_keys = ["68040"]

graphics = "**Apple MEMC video controller with Antelope DAC** 512 KB VRAM standard, 1 MB maximum"

display = '''
External display required
512x384 at 16-bit color
640x480, 800x600, or 832x624 at 8-bit color with 512 KB VRAM; at 16-bit color with 1 MB VRAM
1024x768 or 1152x870 at 4-bit color with 512 KB VRAM; at 8-bit color with 1 MB VRAM
Second display support with additional video card'''
ram = '''
4 MB or 8 MB standard
68 MB maximum
4 MB built-in
2 - 72-pin SIMM slots, 80 ns'''
rom = "1 MB Macintosh ROM"
software = '''
System 7.1 (System Enabler 040 v1.0)
Mac OS 8.1 Maximum'''
storage = '''
80 MB, 230 MB, or 500 MB SCSI hard drive
SCSI hard drive interface
Optional 2x CD-ROM drive
1.44 MB floppy drive'''
features = "1 - Built-in speaker"
expansion = '''
1 - Optional Ethernet port (AAUI-15)
2 - ADB ports
2 - Serial ports
1 - DB-25 SCSI port
1 - DB-15 video port
1 - 3.5-mm mono audio input jack
1 - 3.5-mm stereo audio output jack
1 - 7-inch NuBus or PDS slot'''
design = '''
Platinum
14 lbs.
3.4" H x 16.3" W x 15.6" D'''

support_status = "Obsolete"
sound_profile = "QUADRA"
links = [{ label = "Macintosh Centris 610", url = "https://everymac.com/systems/apple/mac_centris/specs/mac_centris_610.html" }]
