category = "apple_network_server"
picture_asset_key = "MI000144"
name = "Network Server 500"
introductions = [{ year = 1996, month = 2 }]

model_numbers = [{ value = "M3354" }]
order_numbers = [
  { value = "M3468", revisions = ["A"], qualifier = "2.1 GB hard drive and DDS-2 DAT drive" },
  { value = "M3469", revisions = ["A"], qualifier = "no hard drive" },
]

codenames = [{ value = "Shiner LE" }]

processor = "**PowerPC 604** 132 MHz, 0.5 µm process, 32-bit, 16 KB instruction and 16 KB data L1 cache, 512 KB L2 cache, 44 MHz system bus"
processor_family_keys = ["604"]

graphics = "**Cirrus Logic 54M30** 1 MB DRAM framebuffer"

display = "External display support via VGA with DDC-2, up to 1024x768 at 8-bit color"
ram = '''
32 MB standard
512 MB maximum
8 - 168-pin DIMM slots, 60 ns parity or 70 ns nonparity
Matching pairs enable memory interleaving'''
rom = "Open Firmware boot ROM"
software = '''
AIX 4.1.4
AIX 4.1.5 Maximum'''
storage = '''
No hard drive or 2.1 GB Fast/Wide SCSI-2 hard drive
4x CD-ROM drive
Optional 2, 4, or 9 GB Fast/Wide SCSI hard drives
Optional DDS-2 DAT drive
1.44 MB manual-inject floppy drive
Optional 8 mm tape drive'''
features = '''
Hot-swappable drive bays with Apple Network Server PCI RAID Card in RAID 5
Hot-swappable external fans
1 - Built-in speaker'''
expansion = '''
1 - Ethernet port (AAUI-15)
1 - ADB port
2 - DMA mini-DIN-8 serial ports (RS-232/RS-422; LocalTalk and GeoPort cable compatible)
2 - 20 MB/s internal Fast/Wide SCSI-2 channels (up to 7 devices)
1 - 5 MB/s external SCSI-1 port (DB-25, up to 7 devices)
1 - HDI-15 VGA video port
1 - 3.5-mm stereo audio input jack (PlainTalk microphone compatible)
1 - 3.5-mm stereo audio output jack
6 - PCI slots
7 - Front-accessible tray-mount drive bays'''
design = '''
Network Server tower
84 lbs.
24.5" H x 16.5" W x 18" D'''

support_status = "Obsolete"
links = [{ label = "Network Server 500/132", url = "https://everymac.com/systems/apple/network_server/specs/networkserver_500_132.html" }]
