category = "powerbook_duo_68k"
picture_asset_key = "MI000094"
name = "Macintosh PowerBook Duo Dock Plus"
introductions = [{ year = 1995, month = 5 }]

order_numbers = [{ value = "M4219", revisions = ["A"] }]

graphics = "**Apple Duo Dock II video subsystem** 1 MB VRAM"

display = '''
External display support via DB-15
512x384, 640x480, 800x600, or 832x624 at 16-bit color
1024x768 or 1152x870 at 8-bit color'''
storage = '''
Optional internal SCSI hard drive
1.44 MB floppy drive'''
features = '''
External omnidirectional microphone included
1 - Built-in speaker'''
expansion = '''
1 - AAUI-15 Ethernet port
1 - ADB port
2 - RS-422 serial ports
1 - HDI-30 SCSI port
1 - DB-15 video port
1 - Modem pass-through port
1 - 3.5-mm audio input jack
1 - 3.5-mm audio output jack
2 - NuBus slots
1 - 3.5-inch internal hard-drive bay'''
design = '''
13.5 lbs.
5.1" H x 12.3" W x 16.3" D'''

support_status = "Obsolete"
links = [{ label = "PowerBook Duo Dock Plus", url = "https://everymac.com/systems/apple/powerbook_duo/specs/mac_powerbook_duodock_plus.html" }]
