category = "ibook"
picture_asset_key = "MI000249"
name = "iBook G4"
introductions = [{ year = 2003, month = 10 }]

model_numbers = [
  { value = "A1054", qualifier = "12.1-inch" },
  { value = "A1055", qualifier = "14.1-inch" },
]
identifiers = [{ value = "PowerBook6,3" }]
order_numbers = [
  { value = "M9164", revisions = ["A"], qualifier = "12.1-inch" },
  { value = "M9388", revisions = ["A"], qualifier = "14.1-inch 933 MHz" },
  { value = "M9165", revisions = ["A"], qualifier = "14.1-inch 1 GHz" },
]

codenames = [{ value = "Dragon" }, { value = "P72D", qualifier = "12.1-inch" }, { value = "P73D", qualifier = "14.1-inch" }]

processor = '''
**PowerPC 7455 (G4)** 800 MHz, 0.18 µm process, 32-bit, 32 KB instruction and 32 KB data L1 cache, 256 KB on-chip L2 cache, 133 MHz system bus (12.1-inch configuration)
**PowerPC 7455 (G4)** 933 MHz, 0.18 µm process, 32-bit, 32 KB instruction and 32 KB data L1 cache, 256 KB on-chip L2 cache, 133 MHz system bus (14.1-inch configuration)
**PowerPC 7455 (G4)** 1.0 GHz, 0.18 µm process, 32-bit, 32 KB instruction and 32 KB data L1 cache, 256 KB on-chip L2 cache, 133 MHz system bus (14.1-inch configuration)'''
processor_family_keys = ["g4"]
processor_logo_keys = ["7455"]

graphics = "**ATI Mobility Radeon 9200** 32 MB DDR VRAM"
graphics_logo_keys = ["atiradeon2000"]

display = '''
12.1-inch active-matrix color LCD, 1024x768 (800 MHz)
14.1-inch active-matrix color LCD, 1024x768 (933 MHz or 1.0 GHz)
Video mirroring via VGA, composite, or S-video output'''
ram = '''
256 MB standard
640 MB Apple-supported maximum
1152 MB actual maximum
128 MB built-in
1 - PC2100 DDR SO-DIMM slot'''
rom = "New World ROM"
software = '''
Mac OS X 10.3 (7B85)
Mac OS X 10.4.11 Maximum (800 MHz)
Mac OS X 10.5.8 Maximum (933 MHz and faster)
AHT (iBook) 2.0.1, 2.2.1, 2.5'''
storage = '''
30 GB Ultra ATA/100 hard drive standard (800 MHz)
40 GB Ultra ATA/100 hard drive standard (933 MHz)
60 GB Ultra ATA/100 hard drive standard (1.0 GHz)
40 or 60 GB Ultra ATA/100 hard drive configurable
Slot-loading Combo drive (DVD-ROM/CD-RW)
Ultra ATA/100 (ATA-6) hard drive interface'''
features = '''
1 - Optional AirPort Extreme card (802.11b/g)
Optional Bluetooth 1.1
1 - Built-in microphone
2 - Built-in stereo speakers (16-bit, 44.1 kHz sample rate)
50 Wh lithium-ion battery (12-inch)
61 or 62 Wh lithium-ion battery (14-inch)'''
expansion = '''
1 - Ethernet port (10/100BASE-T)
1 - 56 Kbps V.92 modem
2 - USB 2.0 ports
1 - FireWire 400 port
1 - Mini-VGA port
Composite and S-video output via adapter
1 - 3.5-mm audio output jack
1 - Kensington security slot'''
design = '''
Opaque White
4.9 lbs. (12-inch)
5.9 lbs. (14-inch)
1.35" H x 11.2" W x 9.06" D (12-inch)
1.35" H x 12.7" W x 10.2" D (14-inch)'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [
  { label = "iBook G4/800 12-Inch (Original - Op)", url = "https://everymac.com/systems/apple/ibook/specs/ibook_g4_800_12.html" },
  { label = "iBook G4/933 14-Inch (Original - Op)", url = "https://everymac.com/systems/apple/ibook/specs/ibook_g4_933_14.html" },
  { label = "iBook G4/1.0 14-Inch (Original - Op)", url = "https://everymac.com/systems/apple/ibook/specs/ibook_g4_1.0_14.html" },
]
