category = "macbook_pro_intel"
picture_asset_key = "MI000359"
name = "MacBook Pro (15-inch, 2019)"
introductions = [{ year = 2019, month = 5 }]

codenames = [{ value = "J680", qualifier = "MacBookPro15,1" }, { value = "J780", qualifier = "MacBookPro15,3" }]

model_numbers = [{ value = "A1990" }]
identifiers = [
  { value = "MacBookPro15,1" },
  { value = "MacBookPro15,3" },
]
order_numbers = [
  { value = "MV922", revisions = ["A"], qualifier = "2.6 GHz Silver" },
  { value = "MV932", revisions = ["A"], qualifier = "2.3 GHz Silver" },
  { value = "MV902", revisions = ["A"], qualifier = "2.6 GHz Space Gray" },
  { value = "MV912", revisions = ["A"], qualifier = "2.3 GHz Space Gray" },
  { value = "MV942", revisions = ["A"], qualifier = "2.4 GHz Space Gray" },
  { value = "MV952", revisions = ["A"] },
]
emc_numbers = [{ value = "3359" }]

processor = '''
**Intel Core i7 (9750H) ("Coffee Lake")** 2.6 GHz, up to 4.5 GHz, 14 nm process, 64-bit, 6 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 12 MB shared L3 cache
**Intel Core i9 (9880H) ("Coffee Lake")** 2.3 GHz, up to 4.8 GHz, 14 nm process, 64-bit, 8 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 16 MB shared L3 cache
**Intel Core i9 (9980HK) ("Coffee Lake")** 2.4 GHz, up to 5.0 GHz, 14 nm process, 64-bit, 8 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 16 MB shared L3 cache
Intel Direct Media Interface (DMI) 3.0 at 8 GT/s
**Apple T2 (APL1027)**'''
processor_family_keys = ["coffeelake"]
processor_logo_keys = [
  "corei7_9",
  "corei9_9",
  "t2",
]

graphics = '''
**AMD Radeon Pro 555X** 4 GB GDDR5 (2.6 GHz)
**AMD Radeon Pro 560X** 4 GB GDDR5 (2.3 GHz; configurable with 2.6 GHz)
**AMD Radeon Pro Vega 16** 4 GB HBM2 configurable
**AMD Radeon Pro Vega 20** 4 GB HBM2 configurable
**Intel UHD Graphics 630** up to 1.5 GB shared with main memory'''
graphics_logo_keys = [
  "amdradeon2016",
  "amdradeonvega",
  "intelhd",
]

display = '''
15.4-inch (diagonal) LED-backlit display with IPS technology, 2880x1800, 220 ppi, 500 nits, wide color gamut (P3)
Up to two external displays at 5120x2880 at 60 Hz
Up to four external displays at 4096x2304 at 60 Hz
Dual display extended, video mirroring, and AirPlay Mirroring'''
ram = '''
16 GB standard
32 GB configurable
32 GB maximum
PC4-19200 (2400 MHz) DDR4 onboard memory'''
rom = "64-bit EFI"
software = '''
macOS 10.14.5 (18F132)
macOS 15.7.8 Maximum
AirDrop Supported
Handoff Supported
Power Nap Supported
Unlock with Apple Watch Supported'''
storage = '''
256 GB standard (2.6 GHz)
512 GB standard (2.3 GHz)
512 GB, 1, 2, or 4 TB configurable (2.6 GHz)
1, 2, or 4 TB configurable (2.3 GHz)
8.0 GT/s NVMe PCIe x4 flash storage interface'''
features = '''
Wi-Fi (802.11ac)
Bluetooth 5.0
3 - Built-in microphones
2 - Built-in stereo speakers with high dynamic range
Built-in 720p FaceTime HD camera'''
expansion = '''
4 - Thunderbolt 3 ports (up to 40 Gbps; USB 3.1 Gen 2 up to 10 Gbps; digital video output)
1 - 3.5-mm headphone jack'''
design = '''
Silver or Space Gray
Precision aluminum unibody
4.02 lbs.
0.61" H x 13.75" W x 9.48" D'''

support_status = "Vintage"
sound_profile = "T2"
links = [
  { label = "MacBook Pro 15\" \"Core i7\" 2.6 Touch/2019", url = "https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.6-six-core-15-mid-2019-touch-bar-specs.html" },
  { label = "MacBook Pro 15\" \"Core i9\" 2.3 Touch/2019", url = "https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i9-2.3-eight-core-15-mid-2019-touch-bar-specs.html" },
  { label = "MacBook Pro 15\" \"Core i9\" 2.3 Touch/2019 Vega", url = "https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i9-2.3-eight-core-15-mid-2019-touch-bar-vega-16-vega-20-specs.html" },
  { label = "MacBook Pro 15\" \"Core i9\" 2.4 Touch/2019", url = "https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i9-2.4-eight-core-15-mid-2019-touch-bar-specs.html" },
  { label = "MacBook Pro 15\" \"Core i9\" 2.4 Touch/2019 Vega", url = "https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i9-2.4-eight-core-15-mid-2019-touch-bar-vega-16-vega-20-specs.html" },
]
