category = "powerbook_ppc"
picture_asset_key = "MI000224"
name = "PowerBook G4 (12-inch)"
introductions = [{ year = 2003, month = 1 }]

model_numbers = [{ value = "A1010" }]
identifiers = [{ value = "PowerBook6,1" }]
order_numbers = [{ value = "M8760", revisions = ["A"] }]

codenames = [{ value = "Thresher" }, { value = "P99" }]

processor = "**PowerPC 7455 (G4)** 867 MHz, 0.18 µm process, 32-bit, 32 KB instruction and 32 KB data L1 cache, 256 KB on-chip L2 cache, 133 MHz system bus"
processor_family_keys = ["g4"]
processor_logo_keys = ["7455"]

graphics = "**NVIDIA GeForce4 420 Go** 32 MB DDR VRAM"
graphics_logo_keys = ["nvgeforce4"]

display = '''
12.1-inch active-matrix color LCD, 1024x768
Dual display and video mirroring up to 1600x1200'''
ram = '''
256 MB standard
640 MB Apple-supported maximum
1152 MB actual maximum
128 MB built-in
1 - PC2100 DDR SO-DIMM slot'''
rom = "New World ROM"
software = '''
Mac OS X 10.2.3
Mac OS X 10.5.8 Maximum'''
storage = '''
40 GB 4200-rpm Ultra ATA/100 hard drive standard
60 GB 4200-rpm Ultra ATA/100 hard drive configurable
Slot-loading Combo drive (DVD-ROM/CD-RW) standard
Slot-loading SuperDrive (DVD-R/CD-RW) configurable'''
features = '''
Optional AirPort Extreme (802.11b/g)
Bluetooth 1.1
1 - Built-in microphone
2 - Built-in stereo speakers
1 - Built-in midrange-enhancing speaker'''
expansion = '''
1 - Ethernet port (10/100BASE-T)
1 - 56 Kbps V.92 modem
2 - USB 1.1 ports
1 - FireWire 400 port
1 - Mini-VGA port
Composite and S-video output with adapter
1 - 3.5-mm audio input jack
1 - 3.5-mm audio output jack
1 - Kensington security slot'''
design = '''
4.6 lbs.
1.18" H x 10.9" W x 8.6" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [{ label = "PowerBook G4 867 12\" (Al)", url = "https://everymac.com/systems/apple/powerbook_g4/specs/powerbook_g4_867_12.html" }]
