category = "mac_pro_intel"
picture_asset_key = "MI000253"
name = "Mac Pro (Early 2008)"
introductions = [{ year = 2008, month = 1 }]

model_numbers = [{ value = "A1186" }]
identifiers = [{ value = "MacPro3,1" }]
order_numbers = [{ value = "MA970", revisions = ["A"], qualifier = "two 2.8 GHz" }]
emc_numbers = [{ value = "2180" }]

processor = '''
**Intel Xeon E5462 ("Harpertown")** 2.8 GHz, 45 nm process, 64-bit, 4 cores, 32 KB instruction and 32 KB data L1 cache per core, 6 MB shared L2 cache per pair of cores
**Dual Intel Xeon E5462 ("Harpertown")** 2.8 GHz, 45 nm process, 64-bit, 4 cores per processor (8 cores total), 32 KB instruction and 32 KB data L1 cache per core, 6 MB shared L2 cache per pair of cores
**Dual Intel Xeon E5472 ("Harpertown")** 3.0 GHz, 45 nm process, 64-bit, 4 cores per processor (8 cores total), 32 KB instruction and 32 KB data L1 cache per core, 6 MB shared L2 cache per pair of cores
**Dual Intel Xeon X5482 ("Harpertown")** 3.2 GHz, 45 nm process, 64-bit, 4 cores per processor (8 cores total), 32 KB instruction and 32 KB data L1 cache per core, 6 MB shared L2 cache per pair of cores
One or two independent 1.6 GHz frontside buses'''
processor_family_keys = ["penryn"]
processor_logo_keys = ["xeon_a"]

graphics = '''
**ATI Radeon HD 2600 XT** 256 MB GDDR3 SDRAM
**NVIDIA GeForce 8800 GT** 512 MB GDDR3 SDRAM
**NVIDIA Quadro FX 5600** 1.5 GB GDDR3 SDRAM'''
graphics_logo_keys = [
  "atiradeon2007",
  "nvgeforce2008",
  "nvquadro2008",
]

display = "Dual display extended and video mirroring"
ram = '''
2 GB standard
4, 8, 16, or 32 GB configurable
32 GB Apple-supported maximum
64 GB actual maximum
8 - 240-pin PC2-6400 (800 MHz) DDR2 ECC fully-buffered DIMM (FB-DIMM) slots (matched pairs)'''
rom = "64-bit EFI"
software = '''
Mac OS X 10.5.1 (9B2117)
OS X 10.11.6 Maximum
AHT 3A130'''
storage = '''
320 GB 7200-rpm SATA hard drive standard
500 or 750 GB, or 1 TB 7200-rpm SATA hard drives configurable
300 GB 15,000-rpm SAS hard drives configurable
4 TB maximum internal storage
SuperDrive (DVD±R DL/DVD±RW/CD-RW)
4 - 3.0 Gbps Serial ATA (SATA) hard drive interfaces
2 - Ultra ATA/100 optical drive interfaces
2 - 3.0 Gbps Serial ATA (SATA) connectors on logic board'''
features = '''
1 - Optional AirPort Extreme card (802.11a/b/g/n)
Bluetooth 2.0 + EDR
1 - Built-in speaker (24-bit, 44.1 kHz sample rate)'''
expansion = '''
2 - Gigabit Ethernet ports (10/100/1000BASE-T; jumbo frame support)
Optional Apple USB Modem (MA034Z/A)
5 - USB 2.0 ports (500 mA each)
2 - FireWire 400 ports
2 - FireWire 800 ports
28 W total FireWire bus power
1 - Optional dual- or quad-channel 4 Gb Fibre Channel card (MB355G/A or MB356G/A)
2 - Dual-link DVI ports (Radeon HD 2600 XT or GeForce 8800 GT)
2 - Dual-link DVI ports (Quadro FX 5600)
1 - Stereo 3D port (Quadro FX 5600)
1 - 3.5-mm analog input jack
2 - 3.5-mm analog output jacks
1 - Optical S/PDIF input (Toslink; 24-bit, 44.1 kHz)
1 - Optical S/PDIF output (Toslink)
2 - PCI Express 2.0 x16 slots
2 - PCI Express 1.1 x4 slots
4 - Internal 3.5-inch SATA/SAS drive bays (SAS requires Mac Pro RAID Card)
2 - Optical drive bays
1 - Optional Mac Pro RAID Card (256 MB cache; 72-hour cache battery backup)'''
design = '''
42.4 lbs.
20.1" H x 8.1" W x 18.7" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [
  { label = "Mac Pro \"Quad Core\" 2.8 (2008)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-quad-core-2.8-2008-specs.html" },
  { label = "Mac Pro \"Eight Core\" 2.8 (2008)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-eight-core-2.8-2008-specs.html" },
  { label = "Mac Pro \"Eight Core\" 3.0 (2008)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-eight-core-3.0-2008-specs.html" },
  { label = "Mac Pro \"Eight Core\" 3.2 (2008)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-eight-core-3.2-2008-specs.html" },
]
