category = "power_mac_classic"
picture_asset_key = "MI000113"
name = "Power Macintosh 6400"
introductions = [{ year = 1996, month = 10 }]

model_numbers = [{ value = "M3548" }]
gestalt_ids = [{ value = "58" }]
order_numbers = [{ value = "M5427", revisions = ["A"] }]

codenames = [
  { value = "PowerStar", qualifier = "PSX platform" },
  { value = "Hacksaw", qualifier = "system project" },
  { value = "InstaTower", qualifier = "enclosure" },
  { value = "Alchemy", qualifier = "logic board" },
]

processor = '''
**PowerPC 603e (PID7v)** 180 MHz, 0.35 µm process, 32-bit, 16 KB instruction and 16 KB data L1 cache, optional 256 KB L2 cache, 40 MHz system bus
**PowerPC 603e (PID7v)** 200 MHz, 0.35 µm process, 32-bit, 16 KB instruction and 16 KB data L1 cache, 256 KB L2 cache, 40 MHz system bus'''
processor_family_keys = ["603"]

graphics = "**Apple Valkyrie-AR video controller** 1 MB display DRAM"

display = "External display support via DB-15, up to 800x600 at 16-bit color; up to 1024x768 at 8-bit color"
ram = '''
16 MB standard
136 MB maximum
8 MB built-in
2 - 168-pin DIMM slots, 70 ns'''
rom = "4 MB PCI Old World ROM"
software = '''
System 7.5.3 (System Enabler 410 v1.1)
Mac OS 9.1 Maximum'''
storage = '''
1.6 or 2.4 GB IDE hard drive
8x CD-ROM drive
Optional Zip 100 drive
1.44 MB floppy drive
IDE hard drive interface'''
features = '''
1 - Built-in speaker
1 - Built-in subwoofer
1 - Infrared receiver for Apple TV/FM Radio System remote'''
expansion = '''
1 - Optional Ethernet port (10BASE-T)
1 - 28.8 Kbps modem
1 - ADB port
2 - GeoPort serial ports
1 - DB-25 SCSI port
1 - DB-15 video port
1 - TV tuner
1 - FM tuner (F-type connector) with optional Apple TV/FM Radio System
1 - 3.5-mm analog input jack
2 - 3.5-mm analog output jacks
1 - S-video input
1 - RCA video input
2 - RCA audio input jacks with optional Apple Video System card
2 - 7-inch PCI 2.0 slots
1 - Comm II slot
1 - Video input slot
1 - Optional Apple TV/FM Radio System card
1 - 5.25-inch SCSI drive bay (used by optional Zip drive)'''
design = '''
Platinum
44.5 lbs.
16" H x 7.8" W x 16.9" D'''

support_status = "Obsolete"
sound_profile = "POWER_MAC"
links = [{ label = "Power Macintosh 6400/200", url = "https://everymac.com/systems/apple/powermac/specs/powermac_6400_200.html" }]
