category = "powerbook_ppc_classic"
picture_asset_key = "MI000149"
name = "Macintosh PowerBook 2400c"
introductions = [
  { year = 1997, month = 5, qualifier = "180 MHz" },
  { year = 1998, month = 4, qualifier = "240 MHz" },
]

gestalt_ids = [{ value = "307" }]
order_numbers = [
  { value = "M5241", revisions = ["A"], qualifier = "2400c/180" },
  { value = "M6265", revisions = ["A"], qualifier = "2400c/240" },
]

codenames = [
  { value = "Comet", qualifier = "180 MHz" },
  { value = "Nautilus" },
  { value = "Mighty Cat", qualifier = "240 MHz" },
  { value = "Minihooper" },
  { value = "PowerStar", qualifier = "PSX platform" },
]

processor = '''
**PowerPC 603e (PID7v)** 180 MHz, 0.35 µm process, 32-bit, 16 KB instruction and 16 KB data L1 cache, 256 KB L2 cache, 40 MHz system bus
**PowerPC 603e (PID7v)** 240 MHz, 0.35 µm process, 32-bit, 16 KB instruction and 16 KB data L1 cache, 256 KB L2 cache, 40 MHz system bus'''
processor_family_keys = ["603"]

graphics = "**Chips and Technologies 65550 (HiQV32)** 1 MB video RAM"

display = '''
10.4-inch active-matrix color LCD, 800x600 at 16-bit color
External display support up to 800x600 at 16-bit color, or 832x624 and 1024x768 at 8-bit color
Video mirroring at 800x600 and 60 Hz'''
ram = '''
16 MB standard and built-in
48 MB original maximum (180 MHz)
80 MB later Apple-supported maximum
112 MB actual maximum
1 - 144-pin SO-DIMM slot, 60 ns'''
rom = "4 MB PCI Old World ROM"
software = '''
Mac OS 7.6.1 (180 MHz US)
Mac OS 7.6 (180 MHz Japan)
Mac OS 8.1J (240 MHz)
Mac OS 9.1 Maximum'''
storage = '''
1.3 GB ATA hard drive (180 MHz)
2 GB ATA hard drive (240 MHz)
External 1.44 MB floppy drive'''
features = '''
1 - Built-in microphone
1 - Built-in speaker
Infrared, up to 1.152 Mbps'''
expansion = '''
1 - ADB port
1 - RS-422 serial port
1 - HDI-30 SCSI port
1 - External floppy-drive port
1 - HDI-15 video port
1 - 3.5-mm audio input jack
1 - 3.5-mm audio output jack
2 - Type II PC Card slots or 1 - Type III PC Card slot'''
design = '''
4.4 lbs.
1.9" H x 10.5" W x 8.4" D'''

support_status = "Obsolete"
sound_profile = "POWERBOOK"
links = [
  { label = "PowerBook 2400c/180", url = "https://everymac.com/systems/apple/powerbook/specs/mac_powerbook2400c_180.html" },
  { label = "PowerBook 2400c/240", url = "https://everymac.com/systems/apple/powerbook/specs/mac_powerbook2400c_240.html" },
]
