category = "power_mac_classic"
picture_asset_key = "MI000114"
name = "Power Macintosh 7220"
aliases = [
  "Power Macintosh 7220/200",
  "Power Macintosh 7220/200 PC Compatible",
]
introductions = [
  { year = 1997, month = 2, qualifier = "7220/200" },
  { year = 1997, month = 4, qualifier = "7220/200 PC Compatible" },
]

model_numbers = [{ value = "M3959" }]
gestalt_ids = [{ value = "515" }]

codenames = [{ value = "Cupid" }, { value = "Tanzania", qualifier = "logic board" }]

processor = '''
**PowerPC 603e (PID7v)** 200 MHz, 0.35 µm process, 32-bit, 16 KB instruction and 16 KB data L1 cache, 256 KB L2 cache, 40 MHz system bus
**Cyrix 6x86 P166+** 133 MHz, 0.65 µm process, 32-bit, 16 KB unified L1 cache, 66 MHz system bus (PC-compatible configuration)'''
processor_family_keys = ["603"]

graphics = '''
**ATI 264VT-A4S2** 2 MB EDO DRAM
**ATI 264VT-A4S2** 4 MB SGRAM'''

display = "External display support up to 1152x870 at 16-bit color with 2 MB video memory; up to 1280x1024 at 16-bit color with 4 MB video memory"
ram = '''
16 or 32 MB standard
160 MB maximum
3 - 168-pin 3.3-volt unbuffered EDO DIMM slots, 60 ns'''
rom = "4 MB PCI Old World ROM"
software = '''
System 7.5.3 (System Enabler 827)
Mac OS 9.1 Maximum
Windows 95 (PC-compatible configuration)'''
storage = '''
2 GB ATA hard drive
12x CD-ROM drive
1.44 MB floppy drive
ATA hard drive interface'''
features = '''
1 - Built-in microphone
1 - Built-in speaker'''
expansion = '''
1 - Ethernet port (10BASE-T)
1 - ADB port
2 - GeoPort serial ports
1 - DB-25 SCSI port
1 - DB-15 video port
1 - 3.5-mm analog input jack
1 - 3.5-mm analog output jack
2 - PCI slots
1 - Comm II slot
1 - PCI PC Compatibility Card with Cyrix 6x86 P166+ at 133 MHz (PC-compatible configuration)
1 - PC game port (PC-compatible configuration)'''
design = '''
Platinum
24 lbs.
5.43" H x 15.12" W x 17.37" D'''

support_status = "Obsolete"
sound_profile = "POWER_MAC"
links = [{ label = "Power Macintosh 7220/200 (PC)", url = "https://everymac.com/systems/apple/powermac/specs/powermac_7220_200.html" }]
