category = "mac_pro_intel"
picture_asset_key = "MI000253"
name = "Mac Pro (Early 2009)"
introductions = [
  { year = 2009, month = 3, qualifier = "up to 4 TB" },
  { year = 2009, month = 12, qualifier = "up to 8 TB" },
]

model_numbers = [{ value = "A1289" }]
identifiers = [{ value = "MacPro4,1" }]
order_numbers = [
  { value = "MB871", revisions = ["A"], qualifier = "2.66 GHz" },
  { value = "MB535", revisions = ["A"], qualifier = "two 2.26 GHz" },
]
emc_numbers = [{ value = "2314" }]

processor = '''
**Intel Xeon W3520 ("Bloomfield")** 2.66 GHz, up to 2.93 GHz, 45 nm process, 64-bit, 4 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 8 MB fully shared L3 cache, Intel QuickPath Interconnect (QPI) at 4.8 GT/s
**Intel Xeon W3540 ("Bloomfield")** 2.93 GHz, up to 3.2 GHz, 45 nm process, 64-bit, 4 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 8 MB fully shared L3 cache, Intel QuickPath Interconnect (QPI) at 4.8 GT/s
**Intel Xeon W3580 ("Bloomfield")** 3.33 GHz, up to 3.6 GHz, 45 nm process, 64-bit, 4 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 8 MB fully shared L3 cache, Intel QuickPath Interconnect (QPI) at 6.4 GT/s
**Dual Intel Xeon E5520 ("Gainestown")** 2.26 GHz, up to 2.53 GHz, 45 nm process, 64-bit, 4 cores per processor (8 cores total), 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 8 MB fully shared L3 cache per processor, Intel QuickPath Interconnect (QPI) at 5.86 GT/s
**Dual Intel Xeon X5550 ("Gainestown")** 2.66 GHz, up to 3.06 GHz, 45 nm process, 64-bit, 4 cores per processor (8 cores total), 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 8 MB fully shared L3 cache per processor, Intel QuickPath Interconnect (QPI) at 6.4 GT/s
**Dual Intel Xeon X5570 ("Gainestown")** 2.93 GHz, up to 3.33 GHz, 45 nm process, 64-bit, 4 cores per processor (8 cores total), 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 8 MB fully shared L3 cache per processor, Intel QuickPath Interconnect (QPI) at 6.4 GT/s'''
processor_family_keys = ["nehalem"]
processor_logo_keys = ["xeon_b"]

graphics = '''
**NVIDIA GeForce GT 120** 512 MB GDDR3
**ATI Radeon HD 4870** 512 MB GDDR5'''
graphics_logo_keys = [
  "nvgeforce2008",
  "atiradeon2007",
]

display = '''
Up to eight external 30-inch displays with four NVIDIA GeForce GT 120 cards
Digital resolution up to 2560x1600
Analog resolution up to 2048x1536'''
ram = '''
3 GB standard (quad-core)
6 GB standard (8-core)
6, 8, 12, or 16 GB configurable (quad-core)
8, 12, 16, or 32 GB configurable (8-core)
16 GB Apple-supported maximum (quad-core)
32 GB Apple-supported maximum (8-core)
48 GB actual maximum (quad-core)
128 GB actual maximum (8-core; fully usable in OS X 10.9 or later)
4 - 240-pin PC3-8500 (1066 MHz) DDR3 ECC SDRAM slots (quad-core)
8 - 240-pin PC3-8500 (1066 MHz) DDR3 ECC SDRAM slots (8-core)'''
rom = "64-bit EFI"
software = '''
Mac OS X 10.5.6 (9G3553; March 2009)
Mac OS X 10.6 (December 2009)
OS X 10.11.6 Maximum
AHT 3A153'''
storage = '''
640 GB 7200-rpm SATA hard drive standard
1 TB 7200-rpm SATA hard drives configurable (March 2009)
4 TB maximum internal storage (March 2009)
1 or 2 TB 7200-rpm SATA hard drives configurable (December 2009)
8 TB maximum internal storage (December 2009)
SuperDrive (DVD±R DL/DVD±RW/CD-RW)
4 - 3.0 Gbps Serial ATA (SATA) hard drive interfaces'''
features = '''
1 - Optional AirPort Extreme card (802.11a/b/g/n)
Bluetooth 2.1 + EDR
1 - Built-in speaker'''
expansion = '''
2 - Gigabit Ethernet ports (10/100/1000BASE-T; jumbo frame support)
Optional Apple USB Modem (MA034Z/A)
5 - USB 2.0 ports
4 - FireWire 800 ports
1 - Optional dual- or quad-channel 4 Gb Fibre Channel card (MB842G/A or MB843G/A)
1 - 3.5-mm analog input jack
2 - 3.5-mm analog output jacks
1 - Optical S/PDIF input (Toslink; 24-bit, 44.1 kHz)
1 - Optical S/PDIF output (Toslink)
2 - PCI Express 2.0 x16 slots
2 - PCI Express 2.0 x4 slots
4 - Internal 3.5-inch SATA drive bays
2 - Optical drive bays
1 - Optional Mac Pro RAID Card (MB845Z/A)
1 - Mini DisplayPort connector on each graphics card
1 - Dual-link DVI port on each graphics card'''
design = '''
39.9 lbs. (quad-core)
41.2 lbs. (8-core)
20.1" H x 8.1" W x 18.7" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [
  { label = "Mac Pro \"Quad Core\" 2.66 (2009/Nehalem)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-quad-core-2.66-early-2009-nehalem-specs.html" },
  { label = "Mac Pro \"Quad Core\" 2.93 (2009/Nehalem)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-quad-core-2.93-early-2009-nehalem-specs.html" },
  { label = "Mac Pro \"Quad Core\" 3.33 (2009/Nehalem)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-quad-core-3.33-early-2009-nehalem-specs.html" },
  { label = "Mac Pro \"Eight Core\" 2.26 (2009/Nehalem)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-eight-core-2.26-early-2009-nehalem-specs.html" },
  { label = "Mac Pro \"Eight Core\" 2.66 (2009/Nehalem)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-eight-core-2.66-early-2009-nehalem-specs.html" },
  { label = "Mac Pro \"Eight Core\" 2.93 (2009/Nehalem)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-eight-core-2.93-early-2009-nehalem-specs.html" },
]
