category = "imac_intel"
picture_asset_key = "MI000189"
name = "iMac (20-inch Late 2006)"
introductions = [{ year = 2006, month = 9 }]

model_numbers = [{ value = "A1207" }]
identifiers = [{ value = "iMac5,1" }]
order_numbers = [{ value = "MA589", revisions = ["A"] }]
emc_numbers = [{ value = "2118" }]

processor = '''
**Intel Core 2 Duo (T7400) ("Merom")** 2.16 GHz, 65 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 4 MB shared L2 cache, 667 MHz system bus
**Intel Core 2 Duo (T7600) ("Merom")** 2.33 GHz, 65 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 4 MB shared L2 cache, 667 MHz system bus'''
processor_family_keys = ["core"]
processor_logo_keys = ["core2duo"]

graphics = "**ATI Radeon X1600** 128 or 256 MB GDDR3"
graphics_logo_keys = ["atiradeon2004"]

display = '''
20-inch (viewable) widescreen TFT LCD, 1680x1050, 280 nits
External resolution up to 1920x1200 via digital output or 2048x1536 via analog output
Dual display extended and video mirroring'''
ram = '''
1 GB standard
2 or 3 GB configurable
3 GB usable maximum
4 GB physical maximum
2 - 200-pin PC2-5300 (667 MHz) DDR2 SO-DIMM slots'''
rom = "32-bit EFI"
software = '''
Mac OS X 10.4.7 (8K1106)
Mac OS X 10.7.5 Maximum
AHT 3A111'''
storage = '''
250 GB 7200-rpm SATA hard drive standard
500 GB 7200-rpm SATA hard drive configurable
Slot-loading SuperDrive (DVD+R DL/DVD±RW/CD-RW)
1.5 Gbps Serial ATA (SATA) hard drive interface
Ultra ATA/100 (operates at UATA/33) optical drive interface'''
features = '''
1 - Built-in AirPort Extreme card (802.11g; 802.11n capable with optional 802.11n Enabler)
Built-in Bluetooth 2.0 + EDR
1 - Built-in microphone
2 - Built-in stereo speakers
Built-in iSight camera
1 - Infrared receiver for Apple Remote'''
expansion = '''
1 - Gigabit Ethernet port (10/100/1000BASE-T; RJ-45; jumbo frame support)
Optional Apple USB Modem (MA034Z/A)
3 - USB 2.0 ports
2 - FireWire 400 ports (8 W total power)
1 - Mini-DVI port (DVI, VGA, composite and S-video with adapter)
1 - 3.5-mm analog input jack
1 - 3.5-mm analog/optical combo output jack'''
design = '''
White
22 lbs.
18.6" H x 19.4" W x 7.4" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [
  { label = "iMac 20-Inch \"Core 2 Duo\" 2.16", url = "https://everymac.com/systems/apple/imac/specs/imac-core-2-duo-2.16-20-inch-specs.html" },
  { label = "iMac 20-Inch \"Core 2 Duo\" 2.33", url = "https://everymac.com/systems/apple/imac/specs/imac-core-2-duo-2.33-20-inch-specs.html" },
]
