category = "mac_pro_intel"
picture_asset_key = "MI000263"
name = "Mac Pro (2019)"
aliases = ["Mac Pro (Rack, 2019)"]
introductions = [{ year = 2019, month = 6 }]

codenames = [{ value = "J160" }]

model_numbers = [
  { value = "A1991", qualifier = "Tower" },
  { value = "A2304", qualifier = "Rack" },
]
identifiers = [{ value = "MacPro7,1" }]
emc_numbers = [
  { value = "3203", qualifier = "Tower" },
  { value = "3413", qualifier = "Rack" },
]

processor = '''
**Intel Xeon W-3223 ("Cascade Lake")** 3.5 GHz, up to 4.0 GHz, 14 nm process, 64-bit, 8 cores, 32 KB instruction and 32 KB data L1 cache per core, 1 MB L2 cache per core, 16.5 MB shared L3 cache
**Intel Xeon W-3235 ("Cascade Lake")** 3.3 GHz, up to 4.4 GHz, 14 nm process, 64-bit, 12 cores, 32 KB instruction and 32 KB data L1 cache per core, 1 MB L2 cache per core, 19.25 MB shared L3 cache
**Intel Xeon W-3245 ("Cascade Lake")** 3.2 GHz, up to 4.4 GHz, 14 nm process, 64-bit, 16 cores, 32 KB instruction and 32 KB data L1 cache per core, 1 MB L2 cache per core, 22 MB shared L3 cache
**Intel Xeon W-3265M ("Cascade Lake")** 2.7 GHz, up to 4.4 GHz, 14 nm process, 64-bit, 24 cores, 32 KB instruction and 32 KB data L1 cache per core, 1 MB L2 cache per core, 33 MB shared L3 cache
**Intel Xeon W-3275M ("Cascade Lake")** 2.5 GHz, up to 4.4 GHz, 14 nm process, 64-bit, 28 cores, 32 KB instruction and 32 KB data L1 cache per core, 1 MB L2 cache per core, 38.5 MB shared L3 cache
Intel Direct Media Interface (DMI) 3.0 at 8 GT/s
**Apple T2 (APL1027)**'''
processor_family_keys = ["cascadelake"]
processor_logo_keys = [
  "xeon_6",
  "t2",
]

graphics = '''
**AMD Radeon Pro 580X** 8 GB GDDR5
**AMD Radeon Pro W5500X** 8 GB GDDR6
**AMD Radeon Pro W5700X** 16 GB GDDR6
**AMD Radeon Pro Vega II** 32 GB HBM2
**AMD Radeon Pro Vega II Duo** 64 GB HBM2 (32 GB per GPU)
**AMD Radeon Pro W6800X** 32 GB GDDR6
**AMD Radeon Pro W6800X Duo** 64 GB GDDR6 (32 GB per GPU)
**AMD Radeon Pro W6900X** 32 GB GDDR6
**AMD Radeon Pro W6600X** 8 GB GDDR6'''
graphics_logo_keys = [
  "amdradeon2016",
  "amdradeonvega",
]

display = '''
Up to 12 external 4K displays at 3840x2160 and 60 Hz (two Radeon Pro Vega II, Vega II Duo, W6800X, W6900X, or W6800X Duo MPX modules)
Up to 6 external 5K displays at 5120x2880 and 60 Hz (two Radeon Pro W5700X, Vega II, Vega II Duo, W6800X, W6900X, or W6800X Duo MPX modules)
Up to 10 Pro Display XDR or 6K displays at 6016x3384 and 60 Hz (two Radeon Pro W6800X Duo MPX modules)
Extended desktop, video mirroring, and AirPlay Mirroring'''
ram = '''
32 GB standard (4 - 8 GB DIMMs)
48 GB configurable (6 - 8 GB DIMMs)
96 GB configurable (6 - 16 GB DIMMs)
192 GB configurable (6 - 32 GB DIMMs)
384 GB configurable (6 - 64 GB DIMMs)
768 GB configurable (6 - 128 GB DIMMs or 12 - 64 GB DIMMs)
1.5 TB configurable (12 - 128 GB DIMMs; requires 24-core or 28-core processor)
768 GB maximum (8-core, 12-core, or 16-core)
1.5 TB maximum (24-core or 28-core)
2666 MHz DDR4 ECC memory (8-core)
2933 MHz DDR4 ECC memory (12-core to 28-core)
R-DIMM or LR-DIMM; do not mix types
12 - User-accessible 288-pin DDR4 ECC DIMM slots'''
rom = "64-bit EFI"
software = '''
macOS 10.15.2 (19C57)
macOS 26 Maximum
AirDrop Supported
Handoff Supported
Unlock with Apple Watch Supported'''
storage = '''
256 GB SSD standard at launch
512 GB SSD standard after March 2022
512 GB, or 1, 2, 4, or 8 TB SSD configurable at launch
1, 2, 4, or 8 TB SSD configurable after March 2022
1 - module for 256 or 512 GB
2 - modules for 1, 2, 4, or 8 TB
2 - 6.0 Gbps Serial ATA (SATA) hard drive interfaces'''
features = '''
Wi-Fi (802.11ac)
Bluetooth 5.0
1 - Built-in speaker'''
expansion = '''
2 - 10Gb Ethernet ports (NBASE-T at 1, 2.5, 5, or 10 Gbps; RJ-45)
2 - USB 3 ports (USB-A; up to 5 Gbps; Apple I/O card)
4 - Thunderbolt 3 ports (up to 40 Gbps; 2 on Apple I/O card and 2 on top)
2 - HDMI 2.0 ports per MPX module (Radeon Pro 580X, Radeon Pro W5500X, or Radeon Pro W6600X; up to 4096x2160 at 60 Hz)
1 - HDMI 2.0 port per MPX module (Radeon Pro W5700X, Radeon Pro Vega II, Radeon Pro Vega II Duo, Radeon Pro W6800X, Radeon Pro W6800X Duo, or Radeon Pro W6900X; up to 4096x2160 at 60 Hz)
1 - 3.5-mm headphone jack with headset support (Apple I/O card)
8 - PCI Express 3.0 slots
2 - MPX bays for 2 MPX modules or up to 4 PCI Express cards
3 - Full-length PCI Express slots (1 x16 and 2 x8)
1 - Half-length PCI Express x4 slot with Apple I/O card installed'''
design = '''
39.7 lbs. (Tower)
20.8" H x 17.7" W x 8.58" D (Tower)
21.9" H with optional wheels (Tower)
38.8 lbs. (Rack)
8.67" H x 18.98" W x 21.24" D (Rack)'''

support_status = "Supported"
sound_profile = "T2"
links = [
  { label = "Mac Pro \"Eight Core\" 3.5 (2019)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-eight-core-3.5-xeon-w-silver-tower-workstation-2019-specs.html" },
  { label = "Mac Pro \"12-Core\" 3.3 (2019)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-12-core-3.3-xeon-w-silver-tower-workstation-2019-specs.html" },
  { label = "Mac Pro \"16-Core\" 3.2 (2019)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-16-core-3.2-xeon-w-silver-tower-workstation-2019-specs.html" },
  { label = "Mac Pro \"24-Core\" 2.7 (2019)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-24-core-2.7-xeon-w-silver-tower-workstation-2019-specs.html" },
  { label = "Mac Pro \"28-Core\" 2.5 (2019)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-28-core-2.5-xeon-w-silver-tower-workstation-2019-specs.html" },
  { label = "Mac Pro \"Eight Core\" 3.5 (2019 - Rack)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-eight-core-3.5-xeon-w-silver-rack-mountable-2019-specs.html" },
  { label = "Mac Pro \"12-Core\" 3.3 (2019 - Rack)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-12-core-3.3-xeon-w-silver-rack-mountable-2019-specs.html" },
  { label = "Mac Pro \"16-Core\" 3.2 (2019 - Rack)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-16-core-3.2-xeon-w-silver-rack-mountable-2019-specs.html" },
  { label = "Mac Pro \"24-Core\" 2.7 (2019 - Rack)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-24-core-2.7-xeon-w-silver-rack-mountable-2019-specs.html" },
  { label = "Mac Pro \"28-Core\" 2.5 (2019 - Rack)", url = "https://everymac.com/systems/apple/mac_pro/specs/mac-pro-28-core-2.5-xeon-w-silver-rack-mountable-2019-specs.html" },
]
