category = "macbook_intel"
picture_asset_key = "MI000371"
name = "MacBook (13-inch)"
introductions = [{ year = 2006, month = 5 }]

codenames = [{ value = "M42" }]

model_numbers = [{ value = "A1181" }]
identifiers = [{ value = "MacBook1,1" }]
order_numbers = [
  { value = "MA254", revisions = ["A"], qualifier = "White" },
  { value = "MA255", revisions = ["A"], qualifier = "White" },
  { value = "MA472", revisions = ["A"], qualifier = "Black" },
]
emc_numbers = [{ value = "2092" }]

processor = '''
**Intel Core Duo (T2400) ("Yonah")** 1.83 GHz, 65 nm process, 32-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 2 MB shared L2 cache, 667 MHz system bus
**Intel Core Duo (T2500) ("Yonah")** 2.0 GHz, 65 nm process, 32-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 2 MB shared L2 cache, 667 MHz system bus'''
processor_family_keys = ["p6"]
processor_logo_keys = ["coreduo"]

graphics = "**Intel Graphics Media Accelerator (GMA) 950** 64 MB DDR2 shared with main memory (80 MB minimum memory usage)"

display = '''
13.3-inch (diagonal) glossy widescreen display, 1280x800, 114 ppi, 250 nits
One external display up to 1920x1200
Dual display extended and video mirroring'''
ram = '''
512 MB standard
2 GB maximum
2 - 200-pin PC2-5300 (667 MHz) DDR2 SO-DIMM slots'''
rom = "32-bit EFI"
software = '''
Mac OS X 10.4.6 (8I2032)
Mac OS X 10.6.8 Maximum
AHT 3A104'''
storage = '''
60 GB 5400-rpm SATA hard drive standard (1.83 GHz or white 2.0 GHz)
80 GB 5400-rpm SATA hard drive standard (black 2.0 GHz)
80, 100, or 120 GB 5400-rpm SATA hard drive configurable
Slot-loading Combo drive (DVD-ROM/CD-RW) standard (1.83 GHz)
Slot-loading 4x SuperDrive (DVD±RW/CD-RW) standard (2.0 GHz)
1.5 Gbps Serial ATA (SATA) hard drive interface
Ultra ATA/100 (running at UATA/66) optical drive interface'''
features = '''
1 - Built-in AirPort Extreme card (802.11b/g)
Built-in Bluetooth 2.0 + EDR
1 - Built-in microphone
2 - Built-in speakers
Built-in iSight camera
1 - Infrared receiver for Apple Remote'''
expansion = '''
1 - Gigabit Ethernet port (10/100/1000BASE-T; RJ-45; jumbo frame support)
Optional Apple USB Modem (MA034Z/A)
2 - USB 2.0 ports
1 - FireWire 400 port (8 W)
1 - Mini-DVI port (VGA, composite and S-video with adapter)
1 - 3.5-mm analog/optical combo jack
1 - Kensington security slot'''
design = '''
White durable polycarbonate (1.83 or 2.0 GHz) or black durable polycarbonate (2.0 GHz)
5.2 lbs.
1.08" H x 12.78" W x 8.92" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [
  { label = "MacBook \"Core Duo\" 1.83 13\"", url = "https://everymac.com/systems/apple/macbook/specs/macbook_1.83.html" },
  { label = "MacBook \"Core Duo\" 2.0 13\" (White)", url = "https://everymac.com/systems/apple/macbook/specs/macbook_2.0_white.html" },
  { label = "MacBook \"Core Duo\" 2.0 13\" (Black)", url = "https://everymac.com/systems/apple/macbook/specs/macbook_2.0_black.html" },
]
