category = "xserve_ppc"
picture_asset_key = "MI000208"
name = "Xserve G5 (January 2005 Cluster Node)"
introductions = [{ year = 2005, month = 1 }]

model_numbers = [{ value = "A1068" }]
identifiers = [{ value = "RackMac3,1" }]
order_numbers = [{ value = "M9742", revisions = ["A"] }]

codenames = [{ value = "Q42" }, { value = "Q42B", qualifier = "firmware identifier" }]

processor = "**Dual PowerPC 970FX (G5)** 2.3 GHz, 90 nm process, 64-bit, 64 KB instruction and 32 KB data L1 cache per processor, 512 KB on-chip L2 cache per processor, 1.15 GHz system bus per processor"
processor_family_keys = ["g5"]
processor_logo_keys = ["970fx"]

ram = '''
512 MB standard
16 GB maximum
8 - PC3200 184-pin DDR ECC SDRAM slots'''
rom = "New World ROM"
software = '''
Mac OS X Server 10.3.7 (10-client)
Mac OS X Server 10.5.8 Maximum'''
storage = '''
80 GB 7200-rpm SATA hard drive
1 - Hot-plug Apple Drive Module
No optical drive'''
features = '''
Cluster-optimized configuration
Remote monitoring
Front-panel system identifier button'''
expansion = '''
2 - Gigabit Ethernet ports (10/100/1000BASE-T; RJ-45)
2 - USB 2.0 ports
1 - FireWire 400 port
2 - FireWire 800 ports
1 - DB-9 serial port
2 - Full-length 64-bit PCI-X slots (1 card at 133 MHz or 2 cards at 100 MHz; PCI expansion options unavailable as build-to-order)
1 - Hot-plug 3.5-inch SATA drive bay'''
design = '''
1U rack-mountable
33 lbs.
1.73" H x 17.6" W x 28" D'''

support_status = "Obsolete"
sound_profile = "NONE"
links = [{ label = "Xserve G5/2.3 DP Cluster Node", url = "https://everymac.com/systems/apple/xserve/specs/xserve_g5_2.3_dp_node.html" }]
