category = "macbook_air_intel"
picture_asset_key = "MI000388"
name = "MacBook Air (11-inch, Mid 2011)"
introductions = [{ year = 2011, month = 7 }]

model_numbers = [{ value = "A1370" }]
identifiers = [{ value = "MacBookAir4,1" }]
order_numbers = [
  { value = "MC968", revisions = ["A"], qualifier = "64 GB" },
  { value = "MC969", revisions = ["A"], qualifier = "128 GB" },
]
emc_numbers = [{ value = "2471" }]

processor = '''
**Intel Core i5 (2467M) ("Sandy Bridge")** 1.6 GHz, up to 2.3 GHz, 32 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 3 MB shared L3 cache
**Intel Core i7 (2677M) ("Sandy Bridge")** 1.8 GHz, up to 2.9 GHz, 32 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 4 MB shared L3 cache
Intel Direct Media Interface (DMI) at 5 GT/s'''
processor_family_keys = ["snb"]
processor_logo_keys = [
  "corei5_2",
  "corei7_2",
]

graphics = "**Intel HD Graphics 3000** 256 or 384 MB DDR3 SDRAM shared with main memory (dynamically allocated)"
graphics_logo_keys = ["intelhd"]

display = '''
11.6-inch (diagonal) LED-backlit glossy widescreen display, 1366x768
One external Thunderbolt display up to 2560x1600
Dual display extended, video mirroring, and AirPlay Mirroring'''
ram = '''
2 GB standard (64 GB storage configuration)
4 GB standard (128 GB storage configuration)
4 GB configurable (64 GB storage configuration)
4 GB maximum
PC3-10600 (1333 MHz) DDR3 onboard memory'''
rom = "64-bit EFI"
software = '''
Mac OS X 10.7 (11A2063)
macOS 10.13.6 Maximum
AirDrop Supported
Power Nap Supported
AHT 3A223'''
storage = '''
64 or 128 GB flash storage standard (depending on configuration)
256 GB flash storage configurable
Optional external USB MacBook Air SuperDrive
6.0 Gbps Serial ATA (SATA) flash storage interface'''
features = '''
Wi-Fi (802.11n)
Bluetooth 4.0
1 - Built-in microphone
2 - Built-in speakers
Built-in FaceTime camera (640x480)'''
expansion = '''
Optional Apple USB Ethernet Adapter or Thunderbolt to Gigabit Ethernet Adapter
2 - USB 2.0 ports
1 - Thunderbolt 1 port (up to 10 Gbps; digital video output)
1 - 3.5-mm headphone jack'''
design = '''
Precision aluminum unibody
2.38 lbs.
0.11–0.68" H x 11.8" W x 7.56" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [
  { label = "MacBook Air \"Core i5\" 1.6 11\" (Mid-2011)", url = "https://everymac.com/systems/apple/macbook-air/specs/macbook-air-core-i5-1.6-11-mid-2011-specs.html" },
  { label = "MacBook Air \"Core i7\" 1.8 11\" (Mid-2011)", url = "https://everymac.com/systems/apple/macbook-air/specs/macbook-air-core-i7-1.8-11-mid-2011-specs.html" },
]
