category = "macbook_pro_intel"
picture_asset_key = "MI000348"
name = "MacBook Pro (Retina, 13-inch, Late 2012)"
introductions = [{ year = 2012, month = 10 }]

codenames = [{ value = "D1" }]

model_numbers = [{ value = "A1425" }]
identifiers = [{ value = "MacBookPro10,2" }]
order_numbers = [
  { value = "MD212", revisions = ["A"], qualifier = "2.5 GHz with 128 GB storage" },
  { value = "MD213", revisions = ["A"], qualifier = "2.5 GHz with 256 GB storage" },
  { value = "Z0N43", revisions = ["A"], qualifier = "2.5 GHz with 512 GB storage" },
]
emc_numbers = [{ value = "2557" }]

processor = '''
**Intel Core i5 (3210M) ("Ivy Bridge")** 2.5 GHz, up to 3.1 GHz, 22 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 3 MB shared L3 cache
**Intel Core i7 (3520M) ("Ivy Bridge")** 2.9 GHz, up to 3.6 GHz, 22 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 4 MB shared L3 cache
Intel Direct Media Interface (DMI) at 5 GT/s'''
processor_family_keys = ["ivb"]
processor_logo_keys = [
  "corei5_2",
  "corei7_2",
]

graphics = "**Intel HD Graphics 4000** up to 1 GB DDR3 shared with main memory"
graphics_logo_keys = ["intelhd"]

display = '''
13.3-inch (diagonal) LED-backlit display with IPS technology, 2560x1600, 227 ppi
Up to two external Thunderbolt displays
One HDMI-compatible display while using one Thunderbolt display
External resolution up to 1920x1080 via HDMI or 2560x1600 via Thunderbolt
Dual display extended, video mirroring, and AirPlay Mirroring'''
ram = '''
8 GB standard
8 GB maximum
PC3-12800 (1600 MHz) DDR3L onboard memory'''
rom = "64-bit EFI"
software = '''
OS X 10.8.1 (12B2100)
macOS 10.15.7 Maximum
AirDrop Supported
Handoff Supported
Power Nap Supported
AHT 3A242'''
storage = '''
128 GB standard (128 GB configuration)
256 GB standard (256 GB configuration)
256, 512, or 768 GB configurable (128 GB configuration)
512 or 768 GB configurable (256 GB configuration)
Optional Apple USB SuperDrive
6.0 Gbps Serial ATA (SATA) flash storage interface'''
features = '''
Wi-Fi (802.11n)
Bluetooth 4.0
2 - Built-in microphones
2 - Built-in stereo speakers
Built-in 720p FaceTime HD camera'''
expansion = '''
Optional Apple Thunderbolt to Gigabit Ethernet Adapter
2 - USB 3.0 ports (up to 5 Gbps)
Optional Apple Thunderbolt to FireWire Adapter
2 - Thunderbolt 1 ports (up to 10 Gbps)
1 - HDMI port (up to 1920x1080)
1 - 3.5-mm digital/analog headphone jack
1 - Secure Digital (SDXC) card slot'''
design = '''
Precision aluminum unibody
3.57 lbs.
0.75" H x 12.35" W x 8.62" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [
  { label = "MacBook Pro 13\" \"Core i5\" 2.5 Retina 2012", url = "https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i5-2.5-13-late-2012-retina-display-specs.html" },
  { label = "MacBook Pro 13\" \"Core i7\" 2.9 Retina 2012", url = "https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.9-13-late-2012-retina-display-specs.html" },
]
