category = "power_mac"
picture_asset_key = "MI000166"
name = "Power Mac G5 (June 2004)"
introductions = [{ year = 2004, month = 6 }]

model_numbers = [{ value = "A1047" }]
identifiers = [{ value = "PowerMac7,3" }]
order_numbers = [
  { value = "M9454", revisions = ["A"], qualifier = "dual 1.8 GHz" },
  { value = "M9455", revisions = ["A"], qualifier = "dual 2.0 GHz" },
  { value = "M9457", revisions = ["A"], qualifier = "dual 2.5 GHz" },
]
emc_numbers = [{ value = "1969C" }]

codenames = [{ value = "Q77" }, { value = "Niagara" }]

processor = '''
**Dual PowerPC 970FX (G5)** 1.8 GHz, 90 nm process, 64-bit, 64 KB instruction and 32 KB data L1 cache per processor, 512 KB on-chip L2 cache per processor, dual 900 MHz system buses
**Dual PowerPC 970FX (G5)** 2.0 GHz, 90 nm process, 64-bit, 64 KB instruction and 32 KB data L1 cache per processor, 512 KB on-chip L2 cache per processor, dual 1.0 GHz system buses
**Dual PowerPC 970FX (G5)** 2.5 GHz, 90 nm process, 64-bit, 64 KB instruction and 32 KB data L1 cache per processor, 512 KB on-chip L2 cache per processor, dual 1.25 GHz system buses'''
processor_family_keys = ["g5"]
processor_logo_keys = ["970fx"]

graphics = '''
**NVIDIA GeForce FX 5200 Ultra** 64 MB DDR VRAM standard (dual 1.8 GHz and dual 2.0 GHz)
**ATI Radeon 9600 XT** 128 MB DDR VRAM standard (dual 2.5 GHz)
**ATI Radeon 9800 XT** 256 MB DDR VRAM configurable
**NVIDIA GeForce 6800 GT DDL** 256 MB GDDR3 VRAM configurable
**NVIDIA GeForce 6800 Ultra DDL** 256 MB GDDR3 VRAM configurable'''
graphics_logo_keys = [
  "nvgeforcefx",
  "atiradeon2000",
  "nvgeforce6",
]

display = '''
Digital resolution up to 1920x1200 (GeForce FX 5200 Ultra, Radeon 9600 XT, or Radeon 9800 XT)
Digital resolution up to 2560x1600 (GeForce 6800 GT DDL or GeForce 6800 Ultra DDL)
Analog resolution up to 1600x1200
Dual display extended desktop and video mirroring'''
ram = '''
256 MB standard (dual 1.8 GHz)
512 MB standard (dual 2.0 GHz and dual 2.5 GHz)
4 GB maximum (dual 1.8 GHz model)
8 GB maximum (dual 2.0 and 2.5 GHz models)
4 - PC3200 DDR SDRAM slots installed in pairs (dual 1.8 GHz)
8 - PC3200 DDR SDRAM slots installed in pairs (dual 2.0 GHz or 2.5 GHz)'''
rom = "New World ROM"
software = '''
Mac OS X 10.3.4 (7L18 or 7L32)
Mac OS X 10.5.8 Maximum
AHT (Power Mac) 2.2.5, 2.5, 2.5.2'''
storage = '''
80 GB 7200-rpm SATA hard drive standard (dual 1.8 GHz)
160 GB 7200-rpm SATA hard drive standard (dual 2.0 GHz and dual 2.5 GHz)
250 GB 7200-rpm SATA hard drive configurable
SuperDrive (DVD-R/CD-RW)
2 - 1.5 Gbps Serial ATA (SATA) controllers
Ultra ATA/100 optical drive interface'''
features = '''
1 - Optional AirPort Extreme card (802.11b/g) (external antenna)
Optional Bluetooth 1.1
1 - Built-in speaker (24-bit, 44.1 kHz sample rate)'''
expansion = '''
1 - Gigabit Ethernet port (10/100/1000BASE-T; RJ-45)
1 - 56 Kbps V.92 modem
3 - USB 2.0 ports
2 - USB 1.1 ports on the keyboard
2 - FireWire 400 ports
1 - FireWire 800 port
15 W total FireWire bus power
1 - DVI port and 1 - ADC port (GeForce FX 5200 Ultra, Radeon 9600 XT, or Radeon 9800 XT)
2 - Dual-link DVI ports (GeForce 6800 GT DDL or GeForce 6800 Ultra DDL)
1 - 3.5-mm analog audio input jack
1 - 3.5-mm analog audio output jack
1 - Front 3.5-mm headphone jack
1 - Optical S/PDIF input (Toslink)
1 - Optical S/PDIF output (Toslink)
3 - 33 MHz 64-bit PCI slots (dual 1.8 GHz)
2 - 100 MHz 64-bit PCI-X slots (dual 2.0 GHz and faster)
1 - 133 MHz 64-bit PCI-X slot (dual 2.0 GHz and faster)
1 - AGP 8x Pro slot
2 - Internal 3.5-inch SATA drive bays
1 - Optical drive bay'''
design = '''
Aluminum
44.4 lbs.
20.1" H x 8.1" W x 18.7" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [
  { label = "Power Macintosh G5 1.8 DP (PCI)", url = "https://everymac.com/systems/apple/powermac_g5/specs/powermac_g5_1.8_dp_2.html" },
  { label = "Power Macintosh G5 2.0 DP (PCI-X 2)", url = "https://everymac.com/systems/apple/powermac_g5/specs/powermac_g5_2.0_dp_2.html" },
  { label = "Power Macintosh G5 2.5 DP (PCI-X)", url = "https://everymac.com/systems/apple/powermac_g5/specs/powermac_g5_2.5_dp.html" },
]
