category = "power_mac"
picture_asset_key = "MI000151"
name = "Power Macintosh G3 (Desktop)"
introductions = [
  { year = 1997, month = 11, qualifier = "233, 266 MHz" },
  { year = 1998, month = 3, qualifier = "266, 300 MHz" },
]

model_numbers = [{ value = "M3979" }]
gestalt_ids = [{ value = "510" }]
order_numbers = [
  { value = "M6141", revisions = ["A"], qualifier = "233 MHz" },
  { value = "M6202", revisions = ["A"] },
  { value = "M6503", revisions = ["A"], qualifier = "266 MHz" },
  { value = "M7104", revisions = ["A"], qualifier = "300 MHz" },
]

codenames = [{ value = "Gossamer" }]

processor = '''
**PowerPC 750 (G3)** 233 MHz, 0.25 µm process, 32-bit, 32 KB instruction and 32 KB data L1 cache, 512 KB backside (1:2) L2 cache, 66 MHz system bus
**PowerPC 750 (G3)** 266 MHz, 0.25 µm process, 32-bit, 32 KB instruction and 32 KB data L1 cache, 512 KB backside (1:2) L2 cache, 66 MHz system bus
**PowerPC 750 (G3)** 300 MHz, 0.25 µm process, 32-bit, 32 KB instruction and 32 KB data L1 cache, 1 MB backside (1:2) L2 cache, 66 MHz system bus'''
processor_family_keys = ["g3"]
processor_logo_keys = ["750"]

graphics = '''
**ATI 3D Rage II+DVD** 2 MB SGRAM, expandable to 6 MB (233 or 266 MHz)
**ATI 3D Rage Pro PCI** 2 MB SGRAM, expandable to 6 MB (300 MHz)'''
graphics_logo_keys = ["ati"]

display = '''
Single display support via DB-15
2 MB SGRAM: up to 1280x1024 at 8-bit color
4 MB SGRAM: up to 1280x1024 at 16-bit color
6 MB SGRAM: up to 1280x1024 at 32-bit color
Resolutions up to 1600x1200 supported'''
ram = '''
32 MB standard (233 or 266 MHz)
64 MB standard (300 MHz)
384 MB maximum on Revision 1 and 2 logic boards
768 MB maximum on Revision 3 logic boards
3 - PC66 168-pin low-profile SDRAM slots, 10 ns'''
rom = "4 MB PCI Old World ROM"
software = '''
Mac OS 8.0
Mac OS X 10.2.8 Maximum'''
storage = '''
4 GB hard drive standard (233 or 266 MHz)
6 GB hard drive standard (300 MHz)
CD-ROM drive standard
Optional DVD-ROM drive
1.44 MB floppy drive
Optional Zip 100 drive
1 - ATA-2 hard drive bus
2 - SCSI buses (up to 5 MB/s)'''
features = "1 - Built-in speaker"
expansion = '''
1 - Ethernet port (10BASE-T; RJ-45)
1 - Optional 56 Kbps modem
1 - ADB port
2 - Serial ports
1 - DB-25 SCSI port
1 - DB-15 video port
1 - 3.5-mm analog input jack (all cards)
1 - 3.5-mm analog output jack (all cards)
2 - RCA input (Audio/Video Input/Output Card or DVD-Video and Audio/Video Card)
2 - RCA output (Audio/Video Input/Output Card or DVD-Video and Audio/Video Card)
1 - S-video input
1 - RCA video input with optional Audio/Video Input/Output Card or DVD-Video and Audio/Video Card
1 - S-video output
1 - RCA video output with optional Audio/Video Input/Output Card or DVD-Video and Audio/Video Card
3 - PCI slots
1 - 182-pin PERCH (PERCH slot supports Audio Input/Output Card "Whisper", Audio/Video Input/Output Card "Wings", or DVD-Video and Audio/Video Card "Bordeaux")
1 - Modem connector on PERCH cards
2 - 3.5-inch SCSI
1 - ATAPI bay'''
design = '''
Platinum
22.7 lbs.
6.3" H x 14.4" W x 16.9" D'''

support_status = "Obsolete"
sound_profile = "POWER_MAC"
links = [
  { label = "Power Macintosh G3 233 Desktop", url = "https://everymac.com/systems/apple/powermac_g3/specs/powermac_g3_233_dt.html" },
  { label = "Power Macintosh G3 266 Desktop", url = "https://everymac.com/systems/apple/powermac_g3/specs/powermac_g3_266_dt.html" },
  { label = "Power Macintosh G3 300 Desktop", url = "https://everymac.com/systems/apple/powermac_g3/specs/powermac_g3_300_dt.html" },
]
