category = "compact_mac"
picture_asset_key = "MI000007"
name = "Macintosh Classic"
introductions = [{ year = 1990, month = 10 }]

model_numbers = [
  { value = "M0420" },
  { value = "M1420" },
]
gestalt_ids = [{ value = "17" }]
order_numbers = [
  { value = "M0421", revisions = ["A"] },
  { value = "M0435", revisions = ["A"] },
]

codenames = [{ value = "XO" }, { value = "Civic" }]

processor = "**Motorola 68000** 8 MHz, 3.5 µm HMOS process, 16/32-bit, no on-chip cache, 8 MHz system bus"
processor_family_keys = ["68000"]

graphics = "**Apple 1-bit framebuffer** 22 KB shared system memory"

display = "9-inch monochrome display, 512x342, 72 ppi"
ram = '''
1 MB or 2 MB standard
4 MB maximum
1 MB built-in
2 - 30-pin SIMM slots on Memory Expansion Card, 120 ns'''
rom = "512 KB Macintosh ROM"
software = '''
System 6.0.7
System 7.5.5 Maximum'''
storage = '''
Optional 40 MB SCSI hard drive
SCSI hard drive interface
1.44 MB floppy drive'''
features = "1 - Built-in speaker"
expansion = '''
1 - ADB port
2 - Serial ports
1 - DB-25 SCSI port
1 - DB-19 external floppy port
1 - 3.5-mm mono audio output jack'''
design = '''
Platinum
16 lbs.
13.2" H x 9.7" W x 11.2" D'''

support_status = "Obsolete"
sound_profile = "MACINTOSH_128K"
links = [{ label = "Macintosh Classic", url = "https://everymac.com/systems/apple/mac_classic/specs/mac_classic.html" }]
