category = "imac_intel"
picture_asset_key = "MI000278"
name = "iMac (21.5-inch, Late 2011)"
introductions = [{ year = 2011, month = 8 }]

model_numbers = [{ value = "A1311" }]
identifiers = [{ value = "iMac12,1" }]
order_numbers = [{ value = "MC978", revisions = ["A"] }]
emc_numbers = [{ value = "2496" }]

processor = "**Intel Core i3 (2100) (\"Sandy Bridge\")** 3.1 GHz, 32 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 3 MB shared L3 cache, Intel Direct Media Interface (DMI) at 5 GT/s"
processor_family_keys = ["snb"]
processor_logo_keys = ["corei3_2"]

graphics = "**AMD Radeon HD 6750M** 256 MB GDDR5"
graphics_logo_keys = ["amdradeon"]

display = '''
21.5-inch (viewable) LED-backlit glossy widescreen TFT LCD, 1920x1080
External resolution up to 2560x1600
Dual display extended, video mirroring, AirPlay Mirroring, and Target Display'''
ram = '''
2 GB standard
4 or 8 GB configurable
8 GB Apple-supported maximum
16 GB actual maximum
4 - 204-pin PC3-10600 (1333 MHz) DDR3 SO-DIMM slots'''
rom = "64-bit EFI"
software = '''
Mac OS X 10.7 (11A511)
macOS 10.13.6 Maximum
AirDrop Supported
AHT 3A215'''
storage = '''
250 GB 7200-rpm SATA hard drive standard
Slot-loading SuperDrive (DVD±R DL/DVD±RW/CD-RW)
2 - 6.0 Gbps Serial ATA (SATA) hard drive interfaces
3.0 Gbps Serial ATA (SATA) optical drive interface'''
features = '''
Wi-Fi (802.11n)
1 - Built-in microphone
2 - Built-in stereo speakers
2 - Internal 20-watt amplifiers
Built-in FaceTime HD camera'''
expansion = '''
1 - Gigabit Ethernet port (10/100/1000BASE-T; RJ-45)
4 - USB 2.0 ports
1 - FireWire 800 port
1 - Mini DisplayPort connector
1 - 3.5-mm analog/optical combo input jack
1 - 3.5-mm analog/optical combo output jack
1 - Secure Digital (SDXC) card slot'''
design = '''
Silver
19.5 lbs.
17.75" H x 20.8" W x 7.42" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [{ label = "iMac 21.5-Inch \"Core i3\" 3.1 (Late 2011)", url = "https://everymac.com/systems/apple/imac/specs/imac-core-i3-3.1-21-inch-aluminum-late-2011-education-specs.html" }]
