category = "mac_quadra"
picture_asset_key = "MI000033"
name = "Macintosh Quadra 800"
introductions = [{ year = 1993, month = 2 }]

model_numbers = [{ value = "M1206" }]
gestalt_ids = [{ value = "35" }]
order_numbers = [
  { value = "M1287", revisions = ["A"], qualifier = "230 MB hard drive" },
  { value = "M1288", revisions = ["A"], qualifier = "500 MB hard drive" },
  { value = "M1329", revisions = ["A"], qualifier = "230 MB hard drive and CD-ROM" },
]

codenames = [{ value = "Fridge" }, { value = "Wombat 33" }]

processor = "**Motorola 68040** 33 MHz, 0.8 µm HCMOS process, 32-bit, 4 KB instruction and 4 KB data L1 cache, integrated FPU, 33 MHz system bus"
processor_family_keys = ["68040"]

graphics = "**Apple MEMC video controller with Antelope DAC** 512 KB or 1 MB VRAM"

display = '''
External display required
512x384 at 16-bit color
640x480, 800x600, or 832x624 at 8-bit color with 512 KB VRAM; at 16-bit color with 1 MB VRAM
1024x768 or 1152x870 at 4-bit color with 512 KB VRAM; at 8-bit color with 1 MB VRAM
Second display support with additional video card'''
ram = '''
8 MB standard and built-in
136 MB maximum
4 - 72-pin SIMM slots, 60 ns'''
rom = "1 MB Macintosh ROM"
software = '''
System 7.1 (System Enabler 040 v1.0)
Mac OS 8.1 Maximum'''
storage = '''
230 MB, 500 MB, or 1 GB SCSI hard drive
SCSI hard drive interface
Optional 2x CD-ROM drive
1.44 MB floppy drive'''
features = "1 - Built-in speaker"
expansion = '''
1 - Ethernet port (AAUI-15)
2 - ADB ports
2 - Serial ports
1 - DB-25 SCSI port
1 - DB-15 video port
1 - 3.5-mm mono audio input jack
1 - 3.5-mm stereo audio output jack
3 - NuBus slots
1 - 040 PDS slot
1 - 5.25-inch drive bay'''
design = '''
Platinum
24 lbs.
14" H x 7.7" W x 15.75" D'''

support_status = "Obsolete"
sound_profile = "QUADRA"
links = [{ label = "Macintosh Quadra 800", url = "https://everymac.com/systems/apple/mac_quadra/specs/mac_quadra_800.html" }]
