category = "power_mac_classic"
picture_asset_key = "MI000099"
name = "Power Macintosh 8100"
aliases = [
  "Power Macintosh 8115",
  "Power Macintosh 8115/110",
]
introductions = [
  { year = 1994, month = 3, qualifier = "80 MHz" },
  { year = 1994, month = 11, qualifier = "110 MHz" },
  { year = 1995, month = 1, qualifier = "100 MHz" },
  { year = 1995, month = 2, qualifier = "8115/110" },
]

model_numbers = [{ value = "M1688" }]
gestalt_ids = [
  { value = "65", qualifier = "80 MHz" },
  { value = "55", qualifier = "100 MHz" },
  { value = "40", qualifier = "110 MHz" },
]
order_numbers = [
  { value = "M1884", revisions = ["A"] },
  { value = "M1880", revisions = ["A"] },
  { value = "M2199", revisions = ["A"] },
  { value = "M3079", revisions = ["A"] },
  { value = "M2284", revisions = ["A"] },
  { value = "M2297", revisions = ["A"], qualifier = "8100/80" },
  { value = "M2293", revisions = ["A"], qualifier = "8100/80AV" },
  { value = "M3640", revisions = ["A"], qualifier = "8100/100" },
  { value = "M3680", revisions = ["A"], qualifier = "8100/100AV" },
  { value = "M3561", revisions = ["A"], qualifier = "8100/110" },
]

codenames = [{ value = "Cold Fusion", qualifier = "80 and 100 MHz" }, { value = "Flagship", qualifier = "110 MHz and 8115/110" }]

processor = '''
**PowerPC 601** 80 MHz, 0.65 µm process, 32-bit, 32 KB unified L1 cache, 256 KB L2 cache, 40 MHz system bus
**PowerPC 601v** 100 MHz, 0.5 µm process, 32-bit, 32 KB unified L1 cache, 256 KB L2 cache, 33.3 MHz system bus
**PowerPC 601v** 110 MHz, 0.5 µm process, 32-bit, 32 KB unified L1 cache, 256 KB L2 cache, 36.7 MHz system bus'''
processor_family_keys = ["601"]

graphics = '''
**Apple Data Path video subsystem with Ariel II DAC** 640 KB shared system memory
**Apple Power Macintosh 8100 VRAM Expansion Card** 2 MB VRAM standard, 4 MB maximum
**Apple CIVIC AV video subsystem** 2 MB VRAM on AV models'''

display = '''
Dual display support via HDI-45 and DB-15
2 MB VRAM expansion card: up to 1152x870 at 16-bit color
4 MB VRAM expansion card: up to 1152x870 at 24-bit color
AV models: up to 1152x870 at 16-bit color'''
ram = '''
8, 16, or 24 MB standard
264 MB maximum
8 MB built-in
8 - 72-pin SIMM slots installed in pairs, 80 ns'''
rom = "4 MB Old World ROM"
software = '''
System 7.1.2 (80 MHz)
System 7.5 (100 and 110 MHz)
Mac OS 9.1 Maximum'''
storage = '''
250 MB, 500 MB, or 1 GB SCSI hard drive (80 MHz)
700 MB or 1 GB SCSI hard drive (100 MHz)
2 GB SCSI hard drive (110 MHz and 8115/110)
No CD-ROM drive or 2x CD-ROM drive (80 MHz)
2x CD-ROM drive (100 MHz, 110 MHz, and 8115/110)
1.44 MB floppy drive
SCSI hard drive interface'''
features = "1 - Built-in speaker"
expansion = '''
1 - Ethernet port (AAUI-15)
1 - ADB port
2 - GeoPort serial ports
1 - DB-25 SCSI port
1 - HDI-45 audio/video port
1 - DB-15 video port
1 - 3.5-mm analog input jack
1 - 3.5-mm analog output jack
1 - S-video input (AV models)
1 - S-video output (AV models)
3 - 7-inch NuBus slots
1 - PDS slot (Power Macintosh VRAM Upgrade Kit installed on non-AV models, Apple AV card installed on AV models)
1 - 5.25-inch half-height drive bay (used by optional CD-ROM drive)
1 - Additional 3.5-inch drive bay for a hard drive or removable-media device'''
design = '''
Platinum
25.3 lbs.
14" H x 7.7" W x 15.75" D'''

support_status = "Obsolete"
sound_profile = "POWER_MAC_6100"
links = [
  { label = "Power Macintosh 8100/80", url = "https://everymac.com/systems/apple/powermac/specs/powermac_8100_80.html" },
  { label = "Power Macintosh 8100/80AV", url = "https://everymac.com/systems/apple/powermac/specs/powermac_8100_80av.html" },
  { label = "Power Macintosh 8100/100", url = "https://everymac.com/systems/apple/powermac/specs/powermac_8100_100.html" },
  { label = "Power Macintosh 8100/100AV", url = "https://everymac.com/systems/apple/powermac/specs/powermac_8100_100av.html" },
  { label = "Power Macintosh 8100/110", url = "https://everymac.com/systems/apple/powermac/specs/powermac_8100_110.html" },
  { label = "Power Macintosh 8100/110AV", url = "https://everymac.com/systems/apple/powermac/specs/powermac_8100_110av.html" },
  { label = "Power Macintosh 8115/110", url = "https://everymac.com/systems/apple/powermac/specs/powermac_8115_110.html" },
]
