category = "macbook_air_intel"
picture_asset_key = "MI000389"
name = "MacBook Air (13-inch, Mid 2011)"
introductions = [{ year = 2011, month = 7 }]

model_numbers = [{ value = "A1369" }]
identifiers = [{ value = "MacBookAir4,2" }]
order_numbers = [
  { value = "MC965", revisions = ["A"], qualifier = "128 GB" },
  { value = "MC966", revisions = ["A"], qualifier = "256 GB" },
]
emc_numbers = [{ value = "2469" }]

processor = '''
**Intel Core i5 (2557M) ("Sandy Bridge")** 1.7 GHz, up to 2.7 GHz, 32 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 3 MB shared L3 cache
**Intel Core i7 (2677M) ("Sandy Bridge")** 1.8 GHz, up to 2.9 GHz, 32 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 4 MB shared L3 cache
Intel Direct Media Interface (DMI) at 5 GT/s'''
processor_family_keys = ["snb"]
processor_logo_keys = [
  "corei5_2",
  "corei7_2",
]

graphics = "**Intel HD Graphics 3000** 384 MB DDR3 SDRAM shared with main memory"
graphics_logo_keys = ["intelhd"]

display = '''
13.3-inch (diagonal) LED-backlit glossy widescreen display, 1440x900
One external Thunderbolt display up to 2560x1600
Dual display extended, video mirroring, and AirPlay Mirroring'''
ram = '''
4 GB standard
4 GB maximum
PC3-10600 (1333 MHz) DDR3 onboard memory'''
rom = "64-bit EFI"
software = '''
Mac OS X 10.7 (11A2063)
macOS 10.13.6 Maximum
AirDrop Supported
Power Nap Supported
AHT 3A223'''
storage = '''
128 or 256 GB flash storage standard (depending on configuration)
Optional external USB MacBook Air SuperDrive
6.0 Gbps Serial ATA (SATA) flash storage interface'''
features = '''
Wi-Fi (802.11n)
Bluetooth 4.0
1 - Built-in microphone
2 - Built-in speakers
Built-in FaceTime camera (640x480)'''
expansion = '''
Optional Apple USB Ethernet Adapter or Thunderbolt to Gigabit Ethernet Adapter
2 - USB 2.0 ports
1 - Thunderbolt 1 port (up to 10 Gbps; digital video output)
1 - 3.5-mm headphone jack
1 - Secure Digital (SD) card slot'''
design = '''
Precision aluminum unibody
2.96 lbs.
0.11–0.68" H x 12.8" W x 8.94" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [
  { label = "MacBook Air \"Core i5\" 1.7 13\" (Mid-2011)", url = "https://everymac.com/systems/apple/macbook-air/specs/macbook-air-core-i5-1.7-13-mid-2011-specs.html" },
  { label = "MacBook Air \"Core i7\" 1.8 13\" (Mid-2011)", url = "https://everymac.com/systems/apple/macbook-air/specs/macbook-air-core-i7-1.8-13-mid-2011-specs.html" },
  { label = "MacBook Air \"Core i5\" 1.6 13\" (Edu Only)", url = "https://everymac.com/systems/apple/macbook-air/specs/macbook-air-core-i5-1.6-13-early-2012-edu-specs.html" },
]
