category = "mac_mini_intel"
picture_asset_key = "MI000310"
name = "Mac mini Server (Mid 2011)"
introductions = [{ year = 2011, month = 7 }]

model_numbers = [{ value = "A1347" }]
identifiers = [{ value = "Macmini5,3" }]
order_numbers = [{ value = "MC936", revisions = ["A"] }]
emc_numbers = [{ value = "2442" }]

processor = "**Intel Core i7 (2635QM) (\"Sandy Bridge\")** 2.0 GHz, up to 2.9 GHz, 32 nm process, 64-bit, 4 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 6 MB shared L3 cache, Intel Direct Media Interface (DMI) at 5 GT/s"
processor_family_keys = ["snb"]
processor_logo_keys = ["corei7_2"]

graphics = "**Intel HD Graphics 3000** 384 MB DDR3 SDRAM shared with main memory"
graphics_logo_keys = ["intelhd"]

display = '''
One external Thunderbolt display
External resolution up to 2560x1600 via Thunderbolt or 1920x1200 via HDMI
Dual display extended, video mirroring, and AirPlay Mirroring'''
ram = '''
4 GB standard
8 GB configurable
8 GB Apple-supported maximum
16 GB actual maximum
2 - 204-pin PC3-10600 (1333 MHz) DDR3 SO-DIMM slots'''
rom = "64-bit EFI"
software = '''
Mac OS X Server 10.7 (11A2061)
macOS 10.13.6 Maximum
AirDrop Supported
AXD 3X109'''
storage = '''
2 - 500 GB 7200-rpm SATA hard drives standard
2 - 750 GB 7200-rpm SATA hard drives configurable
1 or 2 - 256 GB SSDs configurable
256 GB SSD and 750 GB 7200-rpm hard drive configurable together
Optional external USB MacBook Air SuperDrive
6.0 Gbps Serial ATA (SATA) interface'''
features = '''
Wi-Fi (802.11n)
Bluetooth 4.0
1 - Built-in speaker
1 - Infrared receiver for Apple Remote'''
expansion = '''
1 - Gigabit Ethernet port (10/100/1000BASE-T; RJ-45)
4 - USB 2.0 ports
1 - FireWire 800 port
1 - Thunderbolt 1 port (up to 10 Gbps)
1 - HDMI port (up to 1920x1200)
1 - 3.5-mm analog/optical input jack
1 - 3.5-mm analog/optical combo output jack
1 - Secure Digital (SDXC) card slot'''
design = '''
Silver
3.0 lbs.
1.4" H x 7.7" W x 7.7" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [{ label = "Mac mini \"Core i7\" 2.0 (Mid-2011/Server)", url = "https://everymac.com/systems/apple/mac_mini/specs/mac-mini-core-i7-2.0-mid-2011-server-specs.html" }]
