category = "mac_mini_intel"
picture_asset_key = "MI000310"
name = "Mac mini (Mid 2011)"
introductions = [{ year = 2011, month = 7 }]

model_numbers = [{ value = "A1347" }]
identifiers = [
  { value = "Macmini5,1", qualifier = "2.3 GHz" },
  { value = "Macmini5,2", qualifier = "2.5 or 2.7 GHz" },
]
order_numbers = [
  { value = "MC815", revisions = ["A"], qualifier = "2.3 GHz" },
  { value = "MC816", revisions = ["A"], qualifier = "2.5 GHz" },
]
emc_numbers = [{ value = "2442" }]

processor = '''
**Intel Core i5 (2415M) ("Sandy Bridge")** 2.3 GHz, up to 2.9 GHz, 32 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 3 MB shared L3 cache
**Intel Core i5 (2520M) ("Sandy Bridge")** 2.5 GHz, up to 3.2 GHz, 32 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 3 MB shared L3 cache
**Intel Core i7 (2620M) ("Sandy Bridge")** 2.7 GHz, up to 3.4 GHz, 32 nm process, 64-bit, 2 cores, 32 KB instruction and 32 KB data L1 cache per core, 256 KB L2 cache per core, 4 MB shared L3 cache
Intel Direct Media Interface (DMI) at 5 GT/s'''
processor_family_keys = ["snb"]
processor_logo_keys = [
  "corei5_2",
  "corei7_2",
]

graphics = '''
**AMD Radeon HD 6630M** 256 MB GDDR5 (2.5 and 2.7 GHz)
**Intel HD Graphics 3000** 288 MB DDR3 shared with main memory (2.3 GHz)'''
graphics_logo_keys = [
  "amdradeon",
  "intelhd",
]

display = '''
One external Thunderbolt display with Intel graphics
Up to two external Thunderbolt displays with AMD graphics
External resolution up to 2560x1600 via Thunderbolt or 1920x1200 via HDMI
Dual display extended, video mirroring, and AirPlay Mirroring'''
ram = '''
2 GB standard (2.3 GHz)
4 GB standard (2.5 GHz base)
4 or 8 GB configurable (2.3 GHz base)
8 GB configurable (2.5 GHz base)
8 GB Apple-supported maximum
16 GB actual maximum
2 - 204-pin PC3-10600 (1333 MHz) DDR3 SO-DIMM slots'''
rom = "64-bit EFI"
software = '''
Mac OS X 10.7 (11A2061)
macOS 10.13.6 Maximum
AirDrop Supported
AHT 3A124'''
storage = '''
500 GB 5400-rpm hard drive standard
750 GB 7200-rpm hard drive configurable
256 GB SSD configurable on 2.5 GHz model
256 GB SSD and 750 GB 7200-rpm hard drive configurable together on 2.5 GHz model
Optional external USB MacBook Air SuperDrive
6.0 Gbps Serial ATA (SATA) interface'''
features = '''
Wi-Fi (802.11n)
Bluetooth 4.0
1 - Built-in speaker
1 - Infrared receiver for Apple Remote'''
expansion = '''
1 - Gigabit Ethernet port (10/100/1000BASE-T; RJ-45)
4 - USB 2.0 ports
1 - FireWire 800 port
1 - Thunderbolt 1 port (up to 10 Gbps)
1 - HDMI port (up to 1920x1200)
1 - 3.5-mm analog/optical input jack
1 - 3.5-mm analog/optical combo output jack
1 - Secure Digital (SDXC) card slot'''
design = '''
Silver
2.7 lbs.
1.4" H x 7.7" W x 7.7" D'''

support_status = "Obsolete"
sound_profile = "NEW_WORLD"
links = [
  { label = "Mac mini \"Core i5\" 2.3 (Mid-2011)", url = "https://everymac.com/systems/apple/mac_mini/specs/mac-mini-core-i5-2.3-mid-2011-specs.html" },
  { label = "Mac mini \"Core i5\" 2.5 (Mid-2011)", url = "https://everymac.com/systems/apple/mac_mini/specs/mac-mini-core-i5-2.5-mid-2011-specs.html" },
  { label = "Mac mini \"Core i7\" 2.7 (Mid-2011)", url = "https://everymac.com/systems/apple/mac_mini/specs/mac-mini-core-i7-2.7-mid-2011-specs.html" },
]
