category = "mac_performa_68k"
picture_asset_key = "MI000026"
name = "Macintosh Performa 550"
introductions = [{ year = 1993, month = 10 }]

model_numbers = [{ value = "M1640" }]
gestalt_ids = [{ value = "80" }]
order_numbers = [
  { value = "M2147", revisions = ["A", "B", "C"] },
]

codenames = [{ value = "Hook 33" }]

processor = '''
**Motorola 68030** 33 MHz, 1.3 µm HCMOS process, 32-bit, 0.25 KB instruction and 0.25 KB data L1 cache, 33 MHz system bus
**Optional Motorola 68882 FPU**'''
processor_family_keys = ["68030"]

graphics = "**Apple Ardbeg video controller with Ariel DAC** 512 KB VRAM standard, 768 KB maximum"

display = '''
14-inch Sony Trinitron color display, 640x480 at 8-bit color with 512 KB VRAM; at 16-bit color with 768 KB VRAM
Second display support with LC PDS video card'''
ram = '''
5 MB standard
36 MB maximum
4 MB built-in
1 - 72-pin SIMM slot, 80 ns'''
rom = "1 MB Macintosh ROM"
software = '''
System 7.1P3 (System Enabler 332)
Mac OS 7.6.1 Maximum'''
storage = '''
160 MB SCSI hard drive
2x CD-ROM drive
1.44 MB floppy drive
SCSI hard drive interface'''
features = '''
1 - Built-in microphone
2 - Built-in speakers'''
expansion = '''
2 - ADB ports
2 - Serial ports
1 - DB-25 SCSI port
1 - 3.5-mm analog input jack
2 - 3.5-mm analog output jacks
1 - LC PDS slot'''
design = '''
Platinum
40.5 lbs.
17.9" H x 13.5" W x 16.5" D'''

support_status = "Obsolete"
sound_profile = "QUADRA"
links = [{ label = "Macintosh Performa 550", url = "https://everymac.com/systems/apple/mac_performa/specs/mac_performa_550.html" }]
