category = "powerbook_68k"
picture_asset_key = "MI000083"
name = "Macintosh PowerBook 520, 520c"
aliases = [
  "Macintosh PowerBook 520",
  "Macintosh PowerBook 520c",
]
introductions = [{ year = 1994, month = 5 }]

model_numbers = [{ value = "M4880" }]
gestalt_ids = [{ value = "72" }]

codenames = [{ value = "BlackBird LC" }]

processor = "**Motorola 68LC040** 25 MHz, 0.8 µm HCMOS process, 32-bit, 4 KB instruction and 4 KB data L1 cache, 25 MHz system bus"
processor_family_keys = ["68040"]

graphics = '''
**Chips and Technologies 65220 CSC** 512 KB VRAM for the built-in display
**Apple Keystone video controller with Ariel DAC** 512 KB VRAM for external video'''

display = '''
9.5-inch 4-bit grayscale passive-matrix display, 640x480 (520)
9.5-inch 8-bit color passive-matrix display, 640x480 (520c)
External display up to 832x624
Video mirroring and extended desktop'''
ram = '''
4 MB or 12 MB standard
36 MB maximum
4 MB built-in
1 - PowerBook 5xx memory slot, 70 ns'''
rom = "2 MB Macintosh ROM"
software = '''
System 7.1.1 (PowerBook 500 Series Enabler)
Mac OS 8.1 Maximum'''
storage = '''
160 MB or 240 MB SCSI hard drive (520)
160 MB, 240 MB, or 320 MB SCSI hard drive (520c)
SCSI hard drive interface
1.44 MB floppy drive'''
features = '''
1 - Built-in microphone
2 - Built-in speakers'''
expansion = '''
1 - Ethernet port (AAUI-15)
1 - ADB port
1 - Serial port
1 - HDI-30 SCSI port
1 - Mini-15 video port
1 - 3.5-mm analog audio input jack
1 - 3.5-mm stereo audio output jack
1 - Optional 14.4 Kbps modem
1 - Optional PowerBook PCMCIA Expansion Module supporting 2 - Type II PC Cards or 1 - Type III PC Card
1 - PowerBook expansion bay
1 - 90-pin PDS slot'''
design = '''
6.3 lbs. (520)
6.4 lbs. (520c)
2.3" H x 11.5" W x 9.7" D'''

support_status = "Obsolete"
sound_profile = "QUADRA"
links = [
  { label = "PowerBook 520", url = "https://everymac.com/systems/apple/powerbook/specs/mac_powerbook520.html" },
  { label = "PowerBook 520c", url = "https://everymac.com/systems/apple/powerbook/specs/mac_powerbook520c.html" },
]
