category = "xserve_ppc"
picture_asset_key = "MI000207"
name = "Xserve RAID (SFP Late 2004)"
introductions = [
  { year = 2004, month = 10, qualifier = "up to 5.6 TB" },
  { year = 2005, month = 9, qualifier = "up to 7 TB" },
  { year = 2007, month = 1, qualifier = "up to 10.5 TB" },
]

model_numbers = [{ value = "A1009" }]
order_numbers = [
  { value = "M9721", revisions = ["A"], qualifier = "4 drives; 2004/2005" },
  { value = "M9722", revisions = ["A"], qualifier = "7 drives; 2004" },
  { value = "M9723", revisions = ["A"], qualifier = "14 drives; 2004" },
  { value = "MA208", revisions = ["A"], qualifier = "7 drives; 2005" },
  { value = "MA209", revisions = ["A"], qualifier = "14 drives; 2005" },
]

ram = "1 GB controller cache standard (512 MB per controller)"
rom = "Xserve RAID firmware"
software = "RAID Admin"
storage = '''
4 - 250 GB 7200-rpm Ultra ATA/100 Apple Drive Modules (2004/2005)
7 - 400 GB or 14 - 400 GB 7200-rpm Ultra ATA/100 Apple Drive Modules (2004)
5.6 TB maximum RAID 0 capacity (2004)
7 - 500 GB or 14 - 500 GB 7200-rpm Ultra ATA/100 Apple Drive Modules (2005)
7 TB maximum RAID 0 capacity (2005)
7 - 750 GB or 14 - 750 GB 7200-rpm Ultra ATA/100 Apple Drive Modules (2007)
10.5 TB maximum RAID 0 capacity (2007)
14 - Independent Ultra ATA/100 drive channels'''
features = '''
Dual independent RAID controllers
RAID 0, 1, 3, 5, and 0+1
RAID 10, 30, and 50 (host-based software RAID)
Redundant hot-swappable 450 W power supplies
Redundant hot-swappable cooling modules'''
expansion = '''
2 - 2 Gb Fibre Channel ports (SFP; 200 MB/s per channel)
2 - 10/100BASE-T Ethernet ports for remote management
2 - DB-9 serial ports for UPS systems
14 - Hot-plug 3.5-inch Ultra ATA drive bays'''
design = '''
3U rack-mountable
60-100 lbs.
5.25" H x 17" W x 18.4" D'''

support_status = "Obsolete"
links = [{ label = "Xserve RAID (SFP Late 2004)", url = "https://everymac.com/systems/apple/xserve/specs/xserve_raid_sfp.html" }]
